export const prev = '@paginate/action/PREV'
export const next = '@paginate/action/NEXT'
export const page = '@paginate/action/PAGE'
export const resetPage = '@/paginate/action/RESET_PAGE'
export const _overrideResource = '@/paginate/action/OVERRIDE_RESOURCE'
