export const PREV = '@paginate/mutation/PREV'
export const NEXT = '@paginate/mutation/NEXT'
export const PAGE = '@paginate/mutation/PAGE'
export const RESET_PAGE = '@paginate/mutation/RESET_PAGE'
export const OVERRIDE_RESOURCE = '@paginate/mutation/OVERRIDE_RESOURCE'
